name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex

    steps:
      - uses: actions/checkout@v3

      - name: Install mustache (to update the date)
        run: |
          apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: sayyyho
          destination-repository-name: 2024-Hackathon-4-STAR.T-Frontend
          user-email: ${{ secrets.EMAIL }}
          commit-message: "Automated commit - $(date +%Y-%m-%d)"

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
